import { SearchOutlined } from '@ant-design/icons'
import { Row, Select, Space, Typography,Tag, Col } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import Carousel from '../components/Carousel'
import App from '../components/Item'

export default function Home() {
  return (
    <div style={{width:'100%'}}>
      <Head>
        <title>Guton Kenya LTD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{width:'100%'}}>
      <Carousel />
      <div style={{background:'#141a86',paddingTop:20,borderBottom:'2px solid #141a86'}}>
      <Row justify="center" style={{padding:20}}>
        <Tag icon={<SearchOutlined />} color="#141a86">What Are You Searching For ?</Tag>
      </Row>
      <div className='container' style={{width:'100%',minHeight:100,padding:20,display:'flex',alignItems:'center',flexDirection:"row",gap:20,justifyContent:'space-evenly'}}>
       <Select
       size='large'
        showSearch
        style={{width:'100%'}}
        placeholder="Select Location"
        optionFilterProp="children"
        filterOption={(input, option) => (option?.label ?? '').includes(input)}
        filterSort={(optionA, optionB) =>
          (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
        }
        options={[
          {
            value: '1',
            label: 'Not Identified',
          },
          {
            value: '2',
            label: 'Closed',
          },
          {
            value: '3',
            label: 'Communicated',
          },
          {
            value: '4',
            label: 'Identified',
          },
          {
            value: '5',
            label: 'Resolved',
          },
          {
            value: '6',
            label: 'Cancelled',
          },
        ]}
      />
       <Select
       size='large'
        style={{width:'100%'}}
        showSearch
        placeholder="Select Price"
        optionFilterProp="children"
        filterOption={(input, option) => (option?.label ?? '').includes(input)}
        filterSort={(optionA, optionB) =>
          (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
        }
        options={[
          {
            value: '1',
            label: 'Not Identified',
          },
          {
            value: '2',
            label: 'Closed',
          },
          {
            value: '3',
            label: 'Communicated',
          },
          {
            value: '4',
            label: 'Identified',
          },
          {
            value: '5',
            label: 'Resolved',
          },
          {
            value: '6',
            label: 'Cancelled',
          },
        ]}
      />
       <Select
       size='large'
        showSearch
        style={{width:'100%'}}
        placeholder="Select Area"
        optionFilterProp="children"
        filterOption={(input, option) => (option?.label ?? '').includes(input)}
        filterSort={(optionA, optionB) =>
          (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
        }
        options={[
          {
            value: '1',
            label: 'Not Identified',
          },
          {
            value: '2',
            label: 'Closed',
          },
          {
            value: '3',
            label: 'Communicated',
          },
          {
            value: '4',
            label: 'Identified',
          },
          {
            value: '5',
            label: 'Resolved',
          },
          {
            value: '6',
            label: 'Cancelled',
          },
        ]}
      />
      </div>
      </div>
      <div className='container'>
      <Row justify="start" style={{padding:20}}>
        <Typography.Title>
          Properties For Sale
        </Typography.Title>
      </Row>
      <Row gutter={16}>
        {
          [1,2,3].map(i => (
           <Col xs={24} sm={24} md={8} lg={8} xl={8}>
            <App />
           </Col>
          ))
        }
       </Row>
      </div>
      <div className='container'>
      <Row justify="start" style={{padding:20}}>
        <Typography.Title>
         Land For Sale
        </Typography.Title>
      </Row>
      <Row gutter={16}>
        {
          [1,2,3].map(i => (
           <Col xs={24} sm={24} md={8} lg={8} xl={8}>
            <App />
           </Col>
          ))
        }
       </Row>
      </div>
      </main>
    </div>
  )
}
